version: '3.4'

services:
  app:
    container_name: scheduling_website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      NODE_ENV: development
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: localhost      # Use the service name as the host for the database
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - postgres                 # Ensure PostgreSQL starts before the app
    command: ["npm", "run", "dev"] # Run the dev server with hot reloading

  postgres:
    image: postgres:16            # Use PostgreSQL 14
    container_name: postgres_db
    ports:
      - "5432:5432"               # Expose the default PostgreSQL port
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data

volumes:
  postgres_data:                   # Named volume for persisting database data
      
    