version: '3.4'

services:
  app:
    container_name: scheduling_website
    build:
      context: .
    ports:
      - 7000:3000
    volumes:

      - /usr/src/app/node_modules
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: ./usr/src/app/app
          ignore:
            - node_modules/
        - action: rebuild
          path: /usr/src/app/package.json
    
    environment:
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      NODE_ENV: development
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: localhost   
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - postgres               
    command: ["npm", "run", "dev"]

  postgres:
    image: postgres:16         
    container_name: postgres_db
    ports:
      - "5432:5432"               
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:             
      
    