version: '3.4'

services:
  app:
    container_name: scheduling_website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      NODE_ENV: production